all:
  children:
    noble:
      hosts:
        helium:
          ansible_host: 192.168.10.10
        neon:
          ansible_host: 192.168.10.20
        argon:
          ansible_host: 192.168.10.30
      vars:
        ansible_user: root
        ansible_port: 22
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519_proxmox
        ansible_python_interpreter: /usr/bin/python3
