# SOPS-encrypted. Decrypted in-cluster by sops-secrets-operator into a
# Secret named argocd-oidc-secret, referenced by
# ../argocd-config/argocd-config.yaml's argocd-cm oidc.config
# (clientSecret: $argocd-oidc-secret:oidc.clientSecret). oidc.clientSecret
# must match authentik-oauth-clients.yaml's ARGOCD_OAUTH_CLIENT_SECRET.
# Edit with `sops argocd/dev/manifests/secrets/argocd-oidc.yaml`.
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-oidc-secret
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
spec:
    secretTemplates:
        - name: argocd-oidc-secret
          labels:
            app.kubernetes.io/part-of: argocd
          stringData:
            oidc.clientSecret: ENC[AES256_GCM,data:Odgquh8em5RJ7Z0RhKP+LE7L7P2iu2kdShklCEziNDOtP2uZWJBbPKtBKZrxyIDuoKytI8l/uOXcc1sGtAbuKw==,iv:WVkWce9FhzdW5rdn0A29h/EOd33tRvQd7/MTvi+vcw8=,tag:JqYHj4WrtSVPFFYim7nMmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age123a34n040z2zmwr35yst0ykf3ejnv7f6up6r9kqg9vafsd8rdv6s79cyap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOVdHTTdJMzd2N0hjN1F2
            NVgvUGZhQnpJNjl0WkRvV3NYMFJXMjFmTVZrCkpYYXI2VDd6TDNmaGdIN1dsR1hh
            Z25neVUxckdGbkJOQllrcEVNUyszaDQKLS0tIDZQMlBZUE1mVEZQNzVrTmxRVVpT
            ejRzUDRhTmVDYjA0TTdTRUIzTlR2ODgKyHThdCywEgsDjOTyabUU8O0HW+QgBNFQ
            BaZWAZCilk4HkEWVX1MGyHCLW1+KAz38ZUstgZ7bERPl5LwzckPTpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T12:16:03Z"
    mac: ENC[AES256_GCM,data:3kImqXTJzbLeqFypEoma8lieravtorzDmgZoqzIIdfgLPVUKOKdBqD4Av1jmCUQ4k7TEYcfx35rJEfzP9HrarAtKt6Vq+SstkEle3DEuKSDBZkGdIqkyeRsLlxuYvDNKSy2K1RaHCZ5QjWcWDDauRS2nS3kRrKWm8Vheicl5fz4=,iv:FTyCfXIBOH70K1aKxm0L2dJ7juPtYC5OJ0zwRmaulRM=,tag:WnhuMzxQe2MXTVJztt0Usg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
