# SOPS-encrypted. Decrypted in-cluster by sops-secrets-operator into a
# Secret named authentik-config, referenced by
# ../../values/authentik-values.yaml's authentik.existingSecret.secretName.
# Edit with `sops argocd/dev/manifests/secrets/authentik-config.yaml` -
# never edit the ciphertext by hand. See argocd/README.md's "Secrets
# management" section.
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-config
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-config
          stringData:
            AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:goYxZOQ+bg0SvLU2E42r9rV6IsKCQq3MAbkABPpxqCZKxs5tbzZIwa5FTM85dgeDuMwg8fa/eq/p/yr+NKZfDbsQoAU=,iv:pn4HTlPfuzyz8aNnoWhrTaARMnvyAyzrgVb1agNM2lk=,tag:sSZvG4mXFZFK1LLpTUooGA==,type:str]
            AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:pPkfArQe60X+mEqqeroWKz/lny4=,iv:dj0Sw848N9uvPtMiPwKynu42BCfKpo41cjmUGV0vdJg=,tag:U4xKHo1Z33qa79U37cx7+g==,type:str]
            AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:iSyUCRzvWisp,iv:FwHhrrNMYR7n//mrMfCG6N/fpezxCgXXw0X02/NN0T8=,tag:ZJNWH4kS5f4GMsoa90mCrw==,type:str]
            AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:RyTbpnrwrPkt,iv:hJ+CcUqViGbAQBKAP9bOcnpYRUK/M8CE0EUZVb33l8U=,tag:zWGM43+hzsf4oBZlQ1nJ4Q==,type:str]
            AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:juHbfDUqEl8ZSFFX3BPc7uGDO5tqg38KVWhUrDdSPJAPGqkyZ6JoH7Yskw8+lqEs,iv:4eMRyo+j8LLWi6uehRKlRBYQtyU0PNGmKkQALL8LVto=,tag:Mc5ABckGZcXxgX18eY3AUg==,type:str]
            AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:ijxhfA==,iv:VvDyMRJKAkgFVNSuc2Vfa6cRguzrObOGxE02PhHDWtw=,tag:5dAWhPio9/Kt1Iy7LYaSgw==,type:str]
            AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:vSChdDSHlGprSVuiMDwQWOS15L2dNoRI,iv:ztFpK0V6WbPDNIT2kcv6soHWcpfILiEFVraHp6as84M=,tag:q9ncR2fcmIzCCgvpm0p9xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age123a34n040z2zmwr35yst0ykf3ejnv7f6up6r9kqg9vafsd8rdv6s79cyap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbktUSGgzaFU3SGQxcFBz
            RE9FS2xPWXBQS3pzOUNrakpOWEpXb0FFamxVCk4weFZXWjdrSmI4RWxLU2E4Q1Ew
            Z29kdElxU1Q3VFpwSkt5bmFzeXQ3T1EKLS0tIFpnSkxMSU84Sm5NdDZ5LzFSNkxG
            UlBnTUlCSFgxSWo0UjRITy9LNE9Nbm8KtV5TMSdkhB6Q9W76YYB9P7rXG7K00lgO
            GFo0uUlNMoKGvT0Z6WcvVDO7Vrmq9v0p2+CXwseZreSDS7JRLetOCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T12:16:03Z"
    mac: ENC[AES256_GCM,data:Rk3xe73qZC3mA9ETI+MCCbQTj1lCmVHnOS92/1weLRgMU3EqDlcWxiwGdRVrYeInQaSDtaJDiD5sSDoesvZXsFUEDCjnbjfttRUocSVPfH4PIoOZQKDhqfWBEgU2QefBQKvx2WqeQpTjjEaNREAjhUTGadQ+FMa8x5ozMoQAlqM=,iv:5LIWZa1CfR743WTvWnXK4AmKBnIKyjpJbjAlt+vR1oY=,tag:kSNxohkosBUMyB1PYfPF6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
