# SOPS-encrypted. Decrypted in-cluster by sops-secrets-operator into a
# Secret named authentik-postgresql-secret, referenced by
# ../../values/authentik-values.yaml's postgresql.auth.existingSecret. The
# "password" key must match authentik-config.yaml's
# AUTHENTIK_POSTGRESQL__PASSWORD exactly - both are the same Postgres user's
# password, just consumed by two different charts (the bitnami postgresql
# subchart here, authentik itself over there).
# Edit with `sops argocd/dev/manifests/secrets/authentik-postgresql.yaml`.
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-postgresql
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-postgresql-secret
          stringData:
            postgres-password: ENC[AES256_GCM,data:ePNwpwJw4f2S/F0wfz5kWjiiaOmxqErVKIZhadEVh8T6grC/9TUKc8LIkfxfZqE+,iv:1BJjZuZV8dyBlOuXXZuOOEaSYCRHDKn3TMLbyMIIfwc=,tag:/95Ifw1qQgehAvO7Udvhlg==,type:str]
            password: ENC[AES256_GCM,data:hktVl0WiJpo5w6zAb/G4/VBOgk+oiN3NHB78XpqRkjGzgCxcnDlZwtNYoaXLs0TX,iv:akuBgl/MeqT36ZVmBPd1Ylh2gfShLQBHkDC9hH+NccI=,tag:2HH120Fb+E33wFq5BG1tJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age123a34n040z2zmwr35yst0ykf3ejnv7f6up6r9kqg9vafsd8rdv6s79cyap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteFhDM0lwMm1OVmRBVnZR
            Nnc0bFdocEdJeFJMc0hyaHdhWi8xSWd5ckJzCi9aUVZabzNrc1ZiVTRsT1kwaE1Z
            TU9oZVBlWlhXbVBGRGJ3T1ppTk8rWEEKLS0tIEV2ZkQvbWhmQXdrY1VQZjFpVWNP
            ODJhVm1JNUorbnU4cnZhOHBzQ1k1bHcK02n2tlo0Yj4Jz3YivV3NCn/RGGHsqsbs
            9PPxIieBN0IyOW7yAGvrkK37PTrDnLYtG99mBHe7qX3w1nPEUvztRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T12:16:03Z"
    mac: ENC[AES256_GCM,data:9HrFJGuYU7DAo4rdA/GKFlraITwy6EtBPtlNRw8+a8L1a8k4KZ1wAlPxoYPO00Z5W0F1gvcBaUZuKylJxmYfaJQhBqKxdlQMPbCHtst2q2LP2BXO1e96itwZJeVJ6GWPcdtUoVJbmHaBvj78dlA70yOb4/LcFRIhn+Vkpx8HbTY=,iv:EA8X8rZVk04YNSkfv9iWroCHqRpb9kBUEhp+DG/GpuU=,tag:gRIl8FsKouTnm6vGLUuY3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
