# SOPS-encrypted. Decrypted in-cluster by sops-secrets-operator into a
# Secret named pihole-credentials, referenced by
# ../../values/external-dns-values.yaml's env.
# Edit with `sops argocd/dev/manifests/secrets/pihole.yaml`.
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pihole-credentials
    namespace: external-dns
spec:
    secretTemplates:
        - name: pihole-credentials
          stringData:
            EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:7pfnykdQ7Zg=,iv:bjwU/47HS1OWf216S81YzS4b23z+v4ayittiiS6U9Qk=,tag:SPL+TLIx8mkjTJpX4Wv64A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age123a34n040z2zmwr35yst0ykf3ejnv7f6up6r9kqg9vafsd8rdv6s79cyap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZFNoLzVXZ0NWZUQ1eWp1
            V0xscFQwNzdqR2xIUUxjRjVHZU0ydGh4YXpnCk9uZ0NJYUd1N01FUDVRSDdxNEta
            RUJPeVFVN3dHczd4NlgydkJaRVluNXMKLS0tIG9IN3RDREVyUGlpWkZJOEJ5MStn
            cDdwWWFtU3p2SFFpZzRmQWRHZWswZlkKavkfuWP+VDXIAh7XEldD+j2/zsldfwxx
            GgvA2TJUyFBQUIV+3V7Ot3pUSK4EFPAjC0m10WB8qtiqPU1j+ven9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T22:15:37Z"
    mac: ENC[AES256_GCM,data:SAPb1gdm4RryCNEg/Z/3Yztrn143BHVgioeadOmOCyNWVr3YRGW8EZVbMeQAH6HCUDcmrdDyG6V8/Y9VNWh8own/OYLvWMXs9Y9FRWl08yvVy6r083bogbVBHMkrsFRHlljvrRhHMLLa2QznB6bxPqbQGh9L1cqAYru7WjfwXbo=,iv:A/3CuRAC6tmueuAsU/N46Bz75ohbp4CKJuxTpBgGNGU=,tag:ecuNbZ4SY0YyXnLOzI7CbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
